#!/bin/bash

cat <<EOF1 > /etc/iptables-restore-DOCKER-USER.conf
# Generated by iptables-save v1.6.0 on Fri Aug 10 13:04:02 2018
*filter
:DOCKER-USER - [0:0]
-I DOCKER-USER -s 192.168.88.0/24 -p tcp -m multiport --dports 22,80,443,8080,8888 -j ACCEPT
-I DOCKER-USER -s 192.168.25.0/24 -p tcp -m multiport --dports 22,80,443,8080,8888 -j ACCEPT
-A DOCKER-USER -j RETURN
COMMIT
# Completed on Fri Aug 10 13:04:02 2018
EOF1


cat <<EOF2 > /lib/systemd/system/iptables-restore-DOCKER-USER.service
[Unit]
Description=Restore iptables firewall rules
After=docker.service

[Service]
Type=oneshot
ExecStart=/sbin/iptables-restore -n /etc/iptables-restore-DOCKER-USER.conf

[Install]
WantedBy=multi-user.target
EOF2


systemctl enable iptables-restore-DOCKER-USER.service
systemctl daemon-reload
systemctl start iptables-restore-DOCKER-USER.service

